import type {
  Address,
  AppUser,
  Cart,
  Condiment,
  Dish,
  Listing,
  Notification,
  Order,
  Payment,
  Post,
  SellerProfile,
  UserProfile,
} from '@/types/domain';

const now = new Date();

function iso(offsetDays = 0) {
  const value = new Date(now);
  value.setDate(now.getDate() + offsetDays);
  return value.toISOString();
}

export const demoBuyer: AppUser = {
  id: 'buyer-user-1',
  email: 'buyer@aosell.app',
  role: 'buyer',
  isActive: true,
  createdAt: iso(-20),
  updatedAt: iso(-1),
};

export const demoSellerUser: AppUser = {
  id: 'seller-user-1',
  email: 'seller@aosell.app',
  role: 'seller',
  isActive: true,
  createdAt: iso(-60),
  updatedAt: iso(-1),
};

export const demoUserProfile: UserProfile = {
  userId: demoBuyer.id,
  firstName: 'Amina',
  lastName: 'Kone',
  displayName: 'Amina K.',
  avatarUrl: '',
  phoneNumber: '+49 151 000000',
  bio: 'Curious buyer discovering food, crafts, and services across Europe.',
  city: 'Berlin',
  countryCode: 'DE',
  preferredLanguage: 'de',
  addresses: [],
  createdAt: iso(-20),
  updatedAt: iso(-1),
};

export const demoAddresses: Address[] = [
  {
    id: 'address-1',
    fullName: 'Amina Kone',
    phoneNumber: '+49 151 000000',
    line1: 'Torstrasse 100',
    postalCode: '10119',
    city: 'Berlin',
    countryCode: 'DE',
    instructions: 'Call at arrival',
    isDefault: true,
    createdAt: iso(-8),
    updatedAt: iso(-1),
  },
];

export const demoSellers: SellerProfile[] = [
  {
    id: 'seller-1',
    ownerUserId: 'market-user-1',
    type: 'restaurant',
    brandName: 'Saffron Table',
    description: 'Home-style West African dinners prepared fresh in Berlin.',
    coverImageUrl:
      'https://images.unsplash.com/photo-1665400808116-f0e6339b7e9a?auto=format&fit=crop&w=1200&q=80',
    email: 'hello@saffrontable.de',
    countryCode: 'DE',
    city: 'Berlin',
    deliveryModes: ['aosell', 'seller'],
    verificationStatus: 'verified',
    tags: ['spices', 'meals', 'culture'],
    cuisineSpecialties: ['senegalese', 'guinean'],
    ratingAverage: 4.8,
    ratingCount: 138,
    isOpen: true,
    createdAt: iso(-90),
    updatedAt: iso(-2),
  },
  {
    id: 'seller-2',
    ownerUserId: 'market-user-2',
    type: 'shop',
    brandName: 'Atelier Nomad',
    description: 'Curated design objects, textiles, and handmade decor.',
    coverImageUrl:
      'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1200&q=80',
    email: 'hello@ateliernomad.eu',
    countryCode: 'DE',
    city: 'Hamburg',
    deliveryModes: ['aosell'],
    verificationStatus: 'verified',
    tags: ['decor', 'textiles'],
    cuisineSpecialties: [],
    ratingAverage: 4.7,
    ratingCount: 96,
    isOpen: true,
    createdAt: iso(-120),
    updatedAt: iso(-1),
  },
  {
    id: 'seller-3',
    ownerUserId: 'market-user-3',
    type: 'individual',
    brandName: 'Moussa Fixes',
    description: 'Local handyman services with same-day availability.',
    coverImageUrl:
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    email: 'contact@moussafixes.app',
    countryCode: 'DE',
    city: 'Munich',
    deliveryModes: ['seller'],
    verificationStatus: 'pending',
    tags: ['service', 'repair'],
    cuisineSpecialties: [],
    ratingAverage: 4.5,
    ratingCount: 28,
    isOpen: true,
    createdAt: iso(-50),
    updatedAt: iso(-4),
  },
];

export const demoCondiments: Condiment[] = [
  {
    id: 'condiment-1',
    name: 'Piment',
    normalizedName: 'piment',
    aliases: ['pili-pili', 'piment rouge', 'chili'],
    category: 'spice',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-2',
    name: 'Huile de palme',
    normalizedName: 'huile de palme',
    aliases: ['huile rouge', 'red palm oil'],
    category: 'seasoning',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-3',
    name: 'Cube Maggi',
    normalizedName: 'cube maggi',
    aliases: ['maggi', 'bouillon cube', 'jumbo cube'],
    category: 'seasoning',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-4',
    name: 'Poisson fumé',
    normalizedName: 'poisson fume',
    aliases: ['smoked fish'],
    category: 'protein',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-5',
    name: 'Crevette séchée',
    normalizedName: 'crevette sechee',
    aliases: ['dried shrimp'],
    category: 'protein',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-6',
    name: 'Gombo',
    normalizedName: 'gombo',
    aliases: ['okra', 'lady finger'],
    category: 'vegetable',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-7',
    name: 'Feuille de manioc',
    normalizedName: 'feuille de manioc',
    aliases: ['cassava leaves', 'saka-saka'],
    category: 'vegetable',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-8',
    name: 'Niébé',
    normalizedName: 'niebe',
    aliases: ['black-eyed peas', 'cowpea'],
    category: 'protein',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-9',
    name: 'Bissap',
    normalizedName: 'bissap',
    aliases: ['hibiscus', 'sorrel'],
    category: 'other',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-10',
    name: 'Gari',
    normalizedName: 'gari',
    aliases: ['garri', 'cassava semolina'],
    category: 'starch',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-11',
    name: 'Gingembre',
    normalizedName: 'gingembre',
    aliases: ['ginger'],
    category: 'spice',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-12',
    name: 'Ail',
    normalizedName: 'ail',
    aliases: ['garlic'],
    category: 'spice',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-13',
    name: 'Oignon',
    normalizedName: 'oignon',
    aliases: ['onion'],
    category: 'vegetable',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-14',
    name: 'Tomate concentrée',
    normalizedName: 'tomate concentree',
    aliases: ['tomato paste', 'concentre de tomate'],
    category: 'seasoning',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-15',
    name: "Pâte d'arachide",
    normalizedName: "pate d'arachide",
    aliases: ['peanut paste', 'groundnut paste'],
    category: 'seasoning',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-16',
    name: 'Soumbala',
    normalizedName: 'soumbala',
    aliases: ['dawadawa', 'netetou', 'nere'],
    category: 'seasoning',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-17',
    name: 'Manioc',
    normalizedName: 'manioc',
    aliases: ['cassava'],
    category: 'starch',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-18',
    name: 'Igname',
    normalizedName: 'igname',
    aliases: ['yam'],
    category: 'starch',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-19',
    name: 'Banane plantain',
    normalizedName: 'banane plantain',
    aliases: ['plantain'],
    category: 'starch',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
  {
    id: 'condiment-20',
    name: 'Poisson séché',
    normalizedName: 'poisson seche',
    aliases: ['dried fish', 'poisson sec'],
    category: 'protein',
    createdAt: iso(-90),
    updatedAt: iso(-90),
  },
];

export const demoDishes: Dish[] = [
  {
    id: 'dish-1',
    cuisine: 'senegalese',
    name: 'Thieboudienne',
    slug: 'thieboudienne',
    description: 'Riz, poisson et légumes mijotés dans une sauce tomate-tamarin. Le plat national du Sénégal.',
    defaultCondimentIds: ['condiment-14', 'condiment-4', 'condiment-13', 'condiment-12', 'condiment-1'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-2',
    cuisine: 'senegalese',
    name: 'Yassa poulet',
    slug: 'yassa-poulet',
    description: 'Poulet braisé aux oignons caramélisés, citron et piment.',
    defaultCondimentIds: ['condiment-13', 'condiment-12', 'condiment-1'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-3',
    cuisine: 'senegalese',
    name: 'Fataya',
    slug: 'fataya',
    description: 'Beignet frit farci de poisson ou de viande hachée épicée.',
    defaultCondimentIds: ['condiment-13', 'condiment-1', 'condiment-4'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-4',
    cuisine: 'senegalese',
    name: 'Domoda',
    slug: 'domoda',
    description: "Ragoût à la pâte d'arachide avec viande, légumes, servi avec du riz.",
    defaultCondimentIds: ['condiment-15', 'condiment-14', 'condiment-13'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-5',
    cuisine: 'malian',
    name: 'Mafé',
    slug: 'mafe',
    description: "Ragoût à la pâte d'arachide, viande et légumes, servi avec du riz.",
    defaultCondimentIds: ['condiment-15', 'condiment-14', 'condiment-13', 'condiment-1'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-6',
    cuisine: 'guinean',
    name: 'Riz gras',
    slug: 'riz-gras',
    description: 'Riz riche à la tomate avec viande, poisson et légumes.',
    defaultCondimentIds: ['condiment-14', 'condiment-2', 'condiment-13', 'condiment-4'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-7',
    cuisine: 'guinean',
    name: 'Soupe Kandia',
    slug: 'soupe-kandia',
    description: "Soupe de gombo à l'huile de palme, poisson et viande.",
    defaultCondimentIds: ['condiment-6', 'condiment-2', 'condiment-20'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-8',
    cuisine: 'guinean',
    name: 'Fouti',
    slug: 'fouti',
    description: 'Riz et poisson cuits à la vapeur, enveloppés dans des feuilles.',
    defaultCondimentIds: ['condiment-4', 'condiment-13', 'condiment-1'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-9',
    cuisine: 'ivorian',
    name: 'Alloco',
    slug: 'alloco',
    description: 'Bananes plantains bien mûres frites, servies avec une sauce épicée à l’oignon et à la tomate.',
    defaultCondimentIds: ['condiment-19', 'condiment-13', 'condiment-14', 'condiment-1'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-10',
    cuisine: 'ivorian',
    name: 'Attiéké',
    slug: 'attieke',
    description: 'Semoule de manioc fermenté, servie avec du poisson grillé.',
    defaultCondimentIds: ['condiment-17', 'condiment-4', 'condiment-1'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-11',
    cuisine: 'cameroonian',
    name: 'Ndolé',
    slug: 'ndole',
    description: 'Ragoût de feuilles amères aux arachides, bœuf, crevettes et poisson fumé.',
    defaultCondimentIds: ['condiment-15', 'condiment-5', 'condiment-4'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-12',
    cuisine: 'congolese',
    name: 'Poulet Moambe',
    slug: 'poulet-moambe',
    description: 'Poulet mijoté dans une sauce crémeuse à la noix de palme.',
    defaultCondimentIds: ['condiment-2', 'condiment-13', 'condiment-12'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-13',
    cuisine: 'nigerian',
    name: 'Jollof rice',
    slug: 'jollof-rice',
    description: 'Riz épicé mijoté dans une sauce tomate, cuit en une seule marmite.',
    defaultCondimentIds: ['condiment-14', 'condiment-13', 'condiment-1', 'condiment-3'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-14',
    cuisine: 'ghanaian',
    name: 'Waakye',
    slug: 'waakye',
    description: 'Riz et haricots colorés aux feuilles de mil, servi avec ses accompagnements.',
    defaultCondimentIds: ['condiment-8', 'condiment-10'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-15',
    cuisine: 'beninese',
    name: 'Amiwo',
    slug: 'amiwo',
    description: 'Bouillie de farine de maïs dans une sauce tomate épicée.',
    defaultCondimentIds: ['condiment-14', 'condiment-1', 'condiment-13'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
  {
    id: 'dish-16',
    cuisine: 'togolese',
    name: 'Akoumé',
    slug: 'akoume',
    description: 'Pâte de maïs fermenté, base incontournable servie avec une sauce gombo.',
    defaultCondimentIds: ['condiment-6'],
    createdAt: iso(-80),
    updatedAt: iso(-80),
  },
];

export const demoListings: Listing[] = [
  {
    id: 'listing-1',
    sellerId: 'seller-1',
    type: 'meal',
    title: 'Jollof Dinner Box',
    slug: 'jollof-dinner-box',
    description: 'Smoky jollof rice, grilled chicken, plantains, and fresh salad.',
    price: { amountCents: 1890, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'aosell',
    countryCode: 'DE',
    city: 'Berlin',
    tags: ['meal', 'popular'],
    categories: ['Dinner'],
    media: [
      {
        id: 'listing-1-image-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1665332195309-9d75071138f0?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1665332195309-9d75071138f0?auto=format&fit=crop&w=480&q=70',
        altText: 'Jollof rice with grilled fish, skewers, and fresh vegetables',
        width: 1200,
        height: 900,
        sortOrder: 1,
      },
      {
        id: 'listing-1-image-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1665333048952-a3ee97714c6b?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1665333048952-a3ee97714c6b?auto=format&fit=crop&w=480&q=70',
        altText: 'Fresh plated dinner',
        width: 1200,
        height: 900,
        sortOrder: 2,
      },
    ],
    attributes: [{ key: 'portion', label: 'Portion', value: '1 person' }],
    condiments: [],
    inventory: { isUnlimited: false, quantity: 18 },
    averageRating: 4.8,
    reviewCount: 112,
    linkedVideoUrl: 'https://example.com/jollof.mp4',
    isFeatured: true,
    publishedAt: iso(-12),
    createdAt: iso(-15),
    updatedAt: iso(-1),
  },
  {
    id: 'listing-2',
    sellerId: 'seller-2',
    type: 'product',
    title: 'Indigo Table Runner',
    slug: 'indigo-table-runner',
    description: 'Hand-dyed cotton runner bringing depth and warmth to any table.',
    price: { amountCents: 5400, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'aosell',
    countryCode: 'DE',
    city: 'Hamburg',
    tags: ['home', 'craft'],
    categories: ['Decor'],
    media: [
      {
        id: 'listing-2-image-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=480&q=70',
        altText: 'Textile decor table setting',
        width: 1200,
        height: 900,
        sortOrder: 1,
      },
      {
        id: 'listing-2-image-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=480&q=70',
        altText: 'Warm interior styling details',
        width: 1200,
        height: 900,
        sortOrder: 2,
      },
    ],
    attributes: [{ key: 'material', label: 'Material', value: 'Cotton' }],
    condiments: [],
    inventory: { isUnlimited: false, quantity: 7 },
    averageRating: 4.6,
    reviewCount: 41,
    isFeatured: true,
    publishedAt: iso(-10),
    createdAt: iso(-10),
    updatedAt: iso(-1),
  },
  {
    id: 'listing-3',
    sellerId: 'seller-3',
    type: 'service',
    title: 'Same-Day Furniture Assembly',
    slug: 'same-day-furniture-assembly',
    description: 'Assembly and small repairs for home and office furniture.',
    price: { amountCents: 6900, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'seller',
    countryCode: 'DE',
    city: 'Munich',
    tags: ['service', 'repair'],
    categories: ['Home'],
    media: [
      {
        id: 'listing-3-image-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=480&q=70',
        altText: 'Home repair service setup',
        width: 1200,
        height: 900,
        sortOrder: 1,
      },
      {
        id: 'listing-3-image-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=480&q=70',
        altText: 'Tools prepared for a repair visit',
        width: 1200,
        height: 900,
        sortOrder: 2,
      },
    ],
    attributes: [{ key: 'duration', label: 'Duration', value: '2 hours' }],
    condiments: [],
    inventory: { isUnlimited: true },
    averageRating: 4.5,
    reviewCount: 17,
    isFeatured: false,
    publishedAt: iso(-5),
    createdAt: iso(-5),
    updatedAt: iso(-1),
  },
  {
    id: 'listing-4',
    sellerId: 'seller-1',
    type: 'meal',
    title: 'Weekend Family Platter',
    slug: 'weekend-family-platter',
    description: 'Generous platter for four with grilled fish, rice, sauces, and sides.',
    price: { amountCents: 4800, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'seller',
    countryCode: 'DE',
    city: 'Berlin',
    tags: ['family', 'sharing'],
    categories: ['Lunch'],
    media: [
      {
        id: 'listing-4-image-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1665401015549-712c0dc5ef85?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1665401015549-712c0dc5ef85?auto=format&fit=crop&w=480&q=70',
        altText: 'Grilled fish platter with lemon',
        width: 1200,
        height: 900,
        sortOrder: 1,
      },
      {
        id: 'listing-4-image-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1665332305771-e49a5dd5ba80?auto=format&fit=crop&w=1200&q=80',
        thumbnailUrl:
          'https://images.unsplash.com/photo-1665332305771-e49a5dd5ba80?auto=format&fit=crop&w=480&q=70',
        altText: 'Shared dinner table experience',
        width: 1200,
        height: 900,
        sortOrder: 2,
      },
    ],
    attributes: [{ key: 'portion', label: 'Portion', value: '4 people' }],
    condiments: [],
    inventory: { isUnlimited: false, quantity: 5 },
    averageRating: 4.9,
    reviewCount: 63,
    isFeatured: true,
    publishedAt: iso(-2),
    createdAt: iso(-2),
    updatedAt: iso(-1),
  },
];

// No video-type demo post yet: without a real hosted sample video URL, a fake
// one would visibly break the video player (unlike an image, which degrades
// gracefully). Add one here once a real test video URL is available.
export const demoPosts: Post[] = [
  {
    id: 'post-1',
    sellerId: 'seller-1',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1665332561290-cc6757172890?auto=format&fit=crop&w=1200&q=80',
    mediaWidth: 1200,
    mediaHeight: 900,
    caption: 'Fresh jollof dinner boxes just went out for delivery across Berlin tonight!',
    linkTarget: { type: 'listing', listingId: 'listing-1', sellerId: 'seller-1' },
    likeCount: 34,
    commentCount: 5,
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
  {
    id: 'post-2',
    sellerId: 'seller-1',
    mediaType: 'text',
    caption:
      'We just added Weekend Family Platter for four — perfect for a Sunday get-together. Order ahead, we sell out fast!',
    linkTarget: { type: 'listing', listingId: 'listing-4', sellerId: 'seller-1' },
    likeCount: 12,
    commentCount: 2,
    createdAt: iso(-2),
    updatedAt: iso(-2),
  },
  {
    id: 'post-3',
    sellerId: 'seller-2',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1200&q=80',
    mediaWidth: 1200,
    mediaHeight: 900,
    caption: 'New indigo table runners just landed in the shop — hand-dyed, one of a kind.',
    linkTarget: { type: 'listing', listingId: 'listing-2', sellerId: 'seller-2' },
    likeCount: 21,
    commentCount: 3,
    createdAt: iso(-3),
    updatedAt: iso(-3),
  },
  {
    id: 'post-4',
    sellerId: 'seller-2',
    mediaType: 'text',
    caption: 'Atelier Nomad is open for custom textile orders this month — message us for bespoke sizing.',
    linkTarget: { type: 'seller', sellerId: 'seller-2' },
    likeCount: 8,
    commentCount: 1,
    createdAt: iso(-4),
    updatedAt: iso(-4),
  },
  {
    id: 'post-5',
    sellerId: 'seller-3',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    mediaWidth: 1200,
    mediaHeight: 900,
    caption: 'Same-day furniture assembly slots open this week in Munich — book before Friday.',
    linkTarget: { type: 'listing', listingId: 'listing-3', sellerId: 'seller-3' },
    likeCount: 6,
    commentCount: 0,
    createdAt: iso(-5),
    updatedAt: iso(-5),
  },
  {
    id: 'post-6',
    sellerId: 'seller-1',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1765584830370-085bddbf863f?auto=format&fit=crop&w=1200&q=80',
    mediaWidth: 1200,
    mediaHeight: 900,
    caption: "Behind the scenes: prepping tonight's dinner boxes at Saffron Table.",
    linkTarget: { type: 'seller', sellerId: 'seller-1' },
    likeCount: 45,
    commentCount: 9,
    createdAt: iso(-6),
    updatedAt: iso(-6),
  },
  {
    id: 'post-7',
    sellerId: 'seller-3',
    mediaType: 'text',
    caption: 'Thank you Munich for 100+ five-star repairs this quarter! Booking is open for next week.',
    linkTarget: { type: 'seller', sellerId: 'seller-3' },
    likeCount: 15,
    commentCount: 4,
    createdAt: iso(-7),
    updatedAt: iso(-7),
  },
];

export const demoCart: Cart = {
  id: 'cart-1',
  buyerUserId: demoBuyer.id,
  sellerId: 'seller-1',
  items: [
    {
      listingId: 'listing-1',
      titleSnapshot: 'Jollof Dinner Box',
      unitPriceSnapshot: { amountCents: 1890, currency: 'EUR' },
      quantity: 2,
    },
  ],
  subtotal: { amountCents: 3780, currency: 'EUR' },
  deliveryFee: { amountCents: 450, currency: 'EUR' },
  discount: { amountCents: 0, currency: 'EUR' },
  total: { amountCents: 4230, currency: 'EUR' },
  createdAt: iso(-1),
  updatedAt: iso(-1),
};

export const demoOrders: Order[] = [
  {
    id: 'order-1',
    buyerUserId: demoBuyer.id,
    sellerId: 'seller-1',
    status: 'out_for_delivery',
    items: [
      {
        id: 'order-item-1',
        listingId: 'listing-1',
        titleSnapshot: 'Jollof Dinner Box',
        unitPriceSnapshot: { amountCents: 1890, currency: 'EUR' },
        quantity: 2,
      },
    ],
    subtotal: { amountCents: 3780, currency: 'EUR' },
    deliveryFee: { amountCents: 450, currency: 'EUR' },
    total: { amountCents: 4230, currency: 'EUR' },
    currency: 'EUR',
    deliveryMode: 'aosell',
    deliveryAddress: demoAddresses[0],
    timeline: [
      { status: 'created', at: iso(-2) },
      { status: 'pending_payment', at: iso(-2) },
      { status: 'paid', at: iso(-2) },
      { status: 'confirmed', at: iso(-1) },
      { status: 'preparing', at: iso(-1) },
      { status: 'out_for_delivery', at: iso(0) },
    ],
    notes: 'Extra hot sauce.',
    createdAt: iso(-2),
    updatedAt: iso(0),
  },
];

export const demoPayments: Payment[] = [
  {
    id: 'payment-1',
    orderId: 'order-1',
    provider: 'stripe',
    providerPaymentIntentId: 'pi_demo_123',
    status: 'succeeded',
    amount: { amountCents: 4230, currency: 'EUR' },
    paidAt: iso(-2),
    createdAt: iso(-2),
    updatedAt: iso(-2),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notification-1',
    userId: demoBuyer.id,
    type: 'order_status_changed',
    title: 'Order on the way',
    body: 'Your Jollof Dinner Box is now out for delivery.',
    isRead: false,
    createdAt: iso(0),
  },
  {
    id: 'notification-2',
    userId: demoBuyer.id,
    type: 'listing_published',
    title: 'Fresh family platter added',
    body: 'Saffron Table just published a new sharing platter.',
    isRead: true,
    createdAt: iso(-1),
  },
];
