import type {
  Address,
  AppUser,
  Cart,
  Listing,
  Notification,
  Order,
  Payment,
  SellerProfile,
  UserProfile,
} from '@/types/domain';

const now = new Date();

function iso(offsetDays = 0) {
  const value = new Date(now);
  value.setDate(now.getDate() + offsetDays);
  return value.toISOString();
}

export const demoBuyer: AppUser = {
  id: 'buyer-user-1',
  email: 'buyer@aosell.app',
  role: 'buyer',
  isActive: true,
  createdAt: iso(-20),
  updatedAt: iso(-1),
};

export const demoSellerUser: AppUser = {
  id: 'seller-user-1',
  email: 'seller@aosell.app',
  role: 'seller',
  isActive: true,
  createdAt: iso(-60),
  updatedAt: iso(-1),
};

export const demoUserProfile: UserProfile = {
  userId: demoBuyer.id,
  firstName: 'Amina',
  lastName: 'Kone',
  displayName: 'Amina K.',
  avatarUrl: '',
  phoneNumber: '+49 151 000000',
  bio: 'Curious buyer discovering food, crafts, and services across Europe.',
  city: 'Berlin',
  countryCode: 'DE',
  preferredLanguage: 'de',
  addresses: [],
  createdAt: iso(-20),
  updatedAt: iso(-1),
};

export const demoAddresses: Address[] = [
  {
    id: 'address-1',
    fullName: 'Amina Kone',
    phoneNumber: '+49 151 000000',
    line1: 'Torstrasse 100',
    postalCode: '10119',
    city: 'Berlin',
    countryCode: 'DE',
    instructions: 'Call at arrival',
    isDefault: true,
    createdAt: iso(-8),
    updatedAt: iso(-1),
  },
];

export const demoSellers: SellerProfile[] = [
  {
    id: 'seller-1',
    ownerUserId: 'market-user-1',
    type: 'restaurant',
    brandName: 'Saffron Table',
    description: 'Home-style West African dinners prepared fresh in Berlin.',
    email: 'hello@saffrontable.de',
    countryCode: 'DE',
    city: 'Berlin',
    deliveryModes: ['aosell', 'seller'],
    verificationStatus: 'verified',
    tags: ['spices', 'meals', 'culture'],
    ratingAverage: 4.8,
    ratingCount: 138,
    isOpen: true,
    createdAt: iso(-90),
    updatedAt: iso(-2),
  },
  {
    id: 'seller-2',
    ownerUserId: 'market-user-2',
    type: 'shop',
    brandName: 'Atelier Nomad',
    description: 'Curated design objects, textiles, and handmade decor.',
    email: 'hello@ateliernomad.eu',
    countryCode: 'DE',
    city: 'Hamburg',
    deliveryModes: ['aosell'],
    verificationStatus: 'verified',
    tags: ['decor', 'textiles'],
    ratingAverage: 4.7,
    ratingCount: 96,
    isOpen: true,
    createdAt: iso(-120),
    updatedAt: iso(-1),
  },
  {
    id: 'seller-3',
    ownerUserId: 'market-user-3',
    type: 'individual',
    brandName: 'Moussa Fixes',
    description: 'Local handyman services with same-day availability.',
    email: 'contact@moussafixes.app',
    countryCode: 'DE',
    city: 'Munich',
    deliveryModes: ['seller'],
    verificationStatus: 'pending',
    tags: ['service', 'repair'],
    ratingAverage: 4.5,
    ratingCount: 28,
    isOpen: true,
    createdAt: iso(-50),
    updatedAt: iso(-4),
  },
];

export const demoListings: Listing[] = [
  {
    id: 'listing-1',
    sellerId: 'seller-1',
    type: 'meal',
    title: 'Jollof Dinner Box',
    slug: 'jollof-dinner-box',
    description: 'Smoky jollof rice, grilled chicken, plantains, and fresh salad.',
    price: { amountCents: 1890, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'aosell',
    countryCode: 'DE',
    city: 'Berlin',
    tags: ['meal', 'popular'],
    categories: ['Dinner'],
    media: [],
    attributes: [{ key: 'portion', label: 'Portion', value: '1 person' }],
    inventory: { isUnlimited: false, quantity: 18 },
    averageRating: 4.8,
    reviewCount: 112,
    linkedVideoUrl: 'https://example.com/jollof.mp4',
    isFeatured: true,
    publishedAt: iso(-12),
    createdAt: iso(-15),
    updatedAt: iso(-1),
  },
  {
    id: 'listing-2',
    sellerId: 'seller-2',
    type: 'product',
    title: 'Indigo Table Runner',
    slug: 'indigo-table-runner',
    description: 'Hand-dyed cotton runner bringing depth and warmth to any table.',
    price: { amountCents: 5400, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'aosell',
    countryCode: 'DE',
    city: 'Hamburg',
    tags: ['home', 'craft'],
    categories: ['Decor'],
    media: [],
    attributes: [{ key: 'material', label: 'Material', value: 'Cotton' }],
    inventory: { isUnlimited: false, quantity: 7 },
    averageRating: 4.6,
    reviewCount: 41,
    isFeatured: true,
    publishedAt: iso(-10),
    createdAt: iso(-10),
    updatedAt: iso(-1),
  },
  {
    id: 'listing-3',
    sellerId: 'seller-3',
    type: 'service',
    title: 'Same-Day Furniture Assembly',
    slug: 'same-day-furniture-assembly',
    description: 'Assembly and small repairs for home and office furniture.',
    price: { amountCents: 6900, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'seller',
    countryCode: 'DE',
    city: 'Munich',
    tags: ['service', 'repair'],
    categories: ['Home'],
    media: [],
    attributes: [{ key: 'duration', label: 'Duration', value: '2 hours' }],
    inventory: { isUnlimited: true },
    averageRating: 4.5,
    reviewCount: 17,
    isFeatured: false,
    publishedAt: iso(-5),
    createdAt: iso(-5),
    updatedAt: iso(-1),
  },
  {
    id: 'listing-4',
    sellerId: 'seller-1',
    type: 'meal',
    title: 'Weekend Family Platter',
    slug: 'weekend-family-platter',
    description: 'Generous platter for four with grilled fish, rice, sauces, and sides.',
    price: { amountCents: 4800, currency: 'EUR' },
    status: 'active',
    deliveryMode: 'seller',
    countryCode: 'DE',
    city: 'Berlin',
    tags: ['family', 'sharing'],
    categories: ['Lunch'],
    media: [],
    attributes: [{ key: 'portion', label: 'Portion', value: '4 people' }],
    inventory: { isUnlimited: false, quantity: 5 },
    averageRating: 4.9,
    reviewCount: 63,
    isFeatured: true,
    publishedAt: iso(-2),
    createdAt: iso(-2),
    updatedAt: iso(-1),
  },
];

export const demoCart: Cart = {
  id: 'cart-1',
  buyerUserId: demoBuyer.id,
  sellerId: 'seller-1',
  items: [
    {
      listingId: 'listing-1',
      titleSnapshot: 'Jollof Dinner Box',
      unitPriceSnapshot: { amountCents: 1890, currency: 'EUR' },
      quantity: 2,
    },
  ],
  subtotal: { amountCents: 3780, currency: 'EUR' },
  deliveryFee: { amountCents: 450, currency: 'EUR' },
  total: { amountCents: 4230, currency: 'EUR' },
  createdAt: iso(-1),
  updatedAt: iso(-1),
};

export const demoOrders: Order[] = [
  {
    id: 'order-1',
    buyerUserId: demoBuyer.id,
    sellerId: 'seller-1',
    status: 'out_for_delivery',
    items: [
      {
        id: 'order-item-1',
        listingId: 'listing-1',
        titleSnapshot: 'Jollof Dinner Box',
        unitPriceSnapshot: { amountCents: 1890, currency: 'EUR' },
        quantity: 2,
      },
    ],
    subtotal: { amountCents: 3780, currency: 'EUR' },
    deliveryFee: { amountCents: 450, currency: 'EUR' },
    total: { amountCents: 4230, currency: 'EUR' },
    currency: 'EUR',
    deliveryMode: 'aosell',
    deliveryAddress: demoAddresses[0],
    timeline: [
      { status: 'created', at: iso(-2) },
      { status: 'pending_payment', at: iso(-2) },
      { status: 'paid', at: iso(-2) },
      { status: 'confirmed', at: iso(-1) },
      { status: 'preparing', at: iso(-1) },
      { status: 'out_for_delivery', at: iso(0) },
    ],
    notes: 'Extra hot sauce.',
    createdAt: iso(-2),
    updatedAt: iso(0),
  },
];

export const demoPayments: Payment[] = [
  {
    id: 'payment-1',
    orderId: 'order-1',
    provider: 'stripe',
    providerPaymentIntentId: 'pi_demo_123',
    status: 'succeeded',
    amount: { amountCents: 4230, currency: 'EUR' },
    paidAt: iso(-2),
    createdAt: iso(-2),
    updatedAt: iso(-2),
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notification-1',
    userId: demoBuyer.id,
    type: 'order_status_changed',
    title: 'Order on the way',
    body: 'Your Jollof Dinner Box is now out for delivery.',
    isRead: false,
    createdAt: iso(0),
  },
  {
    id: 'notification-2',
    userId: demoBuyer.id,
    type: 'listing_published',
    title: 'Fresh family platter added',
    body: 'Saffron Table just published a new sharing platter.',
    isRead: true,
    createdAt: iso(-1),
  },
];
